import { SignJWT, jwtVerify } from 'jose';

const JWT_SECRET = envSecret();
const JWT_EXPIRES_IN = '24h';

function envSecret(): string {
    const secret = process.env.JWT_SECRET;
    if (!secret || secret.length < 16) {
        throw new Error(
            'JWT_SECRET environment variable is required (minimum 16 characters)'
        );
    }
    return secret;
}

export interface SyncTokenPayload {
    /** Unique identifier for the desktop client (generated by client) */
    clientId: string;
    /** Issued at timestamp */
    iat: number;
    /** Expiration timestamp */
    exp: number;
}

/**
 * Generate a JWT sync token for a desktop client.
 * The token is signed server-side and used by the desktop app to authenticate
 * with the libsql HTTP endpoint.
 */
export async function generateSyncToken(clientId: string): Promise<string> {
    const secret = new TextEncoder().encode(JWT_SECRET);

    const token = await new SignJWT({ clientId })
        .setProtectedHeader({ alg: 'HS256' })
        .setIssuedAt()
        .setExpirationTime(JWT_EXPIRES_IN)
        .sign(secret);

    return token;
}

/**
 * Verify a JWT sync token and return the payload.
 * Throws if the token is invalid, expired, or malformed.
 */
export async function verifySyncToken(token: string): Promise<SyncTokenPayload> {
    const secret = new TextEncoder().encode(JWT_SECRET);

    const { payload } = await jwtVerify(token, secret, {
        algorithms: ['HS256'],
    });

    return {
        clientId: payload.clientId as string,
        iat: payload.iat as number,
        exp: payload.exp as number,
    };
}
