import { SignJWT, jwtVerify } from 'jose';
import { getServerEnv } from './env';

const JWT_EXPIRES_IN = '24h';

function getSecret(): Uint8Array {
    const env = getServerEnv();
    return new TextEncoder().encode(env.jwtSecret);
}

export interface SyncTokenPayload {
    /** Unique identifier for the desktop client (generated by client) */
    clientId: string;
    /** Issued at timestamp */
    iat: number;
    /** Expiration timestamp */
    exp: number;
}

/**
 * Generate a JWT sync token for a desktop client.
 * The token is signed server-side and used by the desktop app to authenticate
 * with the libsql HTTP endpoint.
 */
export async function generateSyncToken(clientId: string): Promise<string> {
    const secret = getSecret();

    const token = await new SignJWT({ clientId })
        .setProtectedHeader({ alg: 'HS256' })
        .setIssuedAt()
        .setExpirationTime(JWT_EXPIRES_IN)
        .sign(secret);

    return token;
}

/**
 * Verify a JWT sync token and return the payload.
 * Throws if the token is invalid, expired, malformed, or missing required claims.
 */
export async function verifySyncToken(token: string): Promise<SyncTokenPayload> {
    const secret = getSecret();

    const { payload } = await jwtVerify(token, secret, {
        algorithms: ['HS256'],
    });

    if (!payload.clientId || typeof payload.clientId !== 'string') {
        throw new Error('JWT token missing required claim: clientId');
    }
    if (typeof payload.iat !== 'number' || typeof payload.exp !== 'number') {
        throw new Error('JWT token missing required claims: iat, exp');
    }

    return {
        clientId: payload.clientId,
        iat: payload.iat,
        exp: payload.exp,
    };
}
